#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # Set spacevim theme. By default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "palenight"
    colorscheme_bg = "dark"

    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # guifont= 'UbuntuMono Nerd Font Mono:h13'

    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"

    filemanager = "vimfiler"

    # Set disabled plugins.
    #disabled_plugins = ["neomake"]
    lint_on_save = false

    # Set unicode symbol for buffer and window index
    # 0: 1 ➛ ➊
    # 1: 1 ➛ ➀
    # 2: 1 ➛ ⓵
    # 3: 1 ➛ ¹
    # 4: 1 ➛ 1
    buffer_index_type = 1
    windows_index_type = 1
    
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    statusline_unicode_symbols = true

    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after' 

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

# Enable shell
[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

# Enable colorscheme
[[layers]]
name = "colorscheme"

# Enable denite
[[layers]]
name = "ctrlp"

# Enable tools (bookmarks, etc.)
[[layers]]
name = "tools"

# Install vim-latex
[[custom_plugins]]
repo = "vim-latex/vim-latex"
merged = false

# Install thesaurus_query plugin
[[custom_plugins]]
repo = "Ron89/thesaurus_query.vim"
merged = false

# Install colorizer
[[custom_plugins]]
repo = "lilydjwg/colorizer"
on_cmd = ["ColorHighlight", "ColorToggle"]
merged = false
